env: "local"
grpc_server:
  host: "localhost"
  port: "50052"
user_db:
  dsn: "host=user-db user=postgres password=admin dbname=shvark_user_service port=5432 sslmode=disable"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"